AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A reaktor hello world alexa skill.
Resources:
  UpdateSatelliteTleFunction:
    Type: Schedule
    Properties:
      Schedule: rate(5 minutes)
      Handler: updateSatelliteTle.handler
      Runtime: nodejs8.10
      CodeUri: ./src/
  