AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A reaktor hello world alexa skill.
Resources:
  UpdateSatelliteTleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateSatelliteTle.handler
      Runtime: nodejs8.10
      CodeUri: ./build/updateSatelliteTle/
    Events:
      StartJob:
        Type: Schedule
        Properties:
          Schedule: rate(6 hours)
  SimpleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: ReaktorHelloWorldTle
      Description: 'Cache for Reaktor Hello World Satellite TLE in JSON'
      Type: String
      Value: '{}'
